#!/usr/bin/env python3
"""Generates known-answer vectors for the MFS_1 access scheme.

A THIRD, INDEPENDENT IMPLEMENTATION. The firmware (PSA on target, OpenSSL on the
host) and the app (pointycastle) must each reproduce these bytes exactly. Python's
`cryptography` package is the reference because it is neither of the two
implementations under test - a vector generated by one side and checked by the
same side proves nothing.

Scheme: docs/tan-scheme.md. Run from the class_mfs_1 root:
    python3 tools/gen_access_vectors.py
"""
import hashlib
import hmac
import pathlib
import struct

from cryptography.hazmat.primitives.ciphers.aead import AESCCM

LABEL_DAY_KEY = 0x02
LABEL_ENC_KEY = 0x03
LABEL_ROTATING_ID = 0x04
LABEL_TIME_SYNC = 0x05
PROTOCOL_VERSION = 0x04
TAG_BYTES = 4

SECRET = bytes(range(0x00, 0x20))          # bench secret 00 01 .. 1F
PROVISION_KEY = bytes(range(0x20, 0x40))   # bench provisioning key 20 .. 3F
DEVICE_ID = 0x4D465331                     # 'MFS1'


def hmac256(key: bytes, message: bytes) -> bytes:
    return hmac.new(key, message, hashlib.sha256).digest()


def day_key(secret: bytes, device_id: int, day: int, slot: int) -> bytes:
    return hmac256(secret, struct.pack(">IHB", device_id, day, slot) + bytes([LABEL_DAY_KEY]))


def enc_key(dk: bytes) -> bytes:
    return hmac256(dk, bytes([LABEL_ENC_KEY]))[:16]


def rotating_id(dk: bytes, n: int) -> bytes:
    return hmac256(dk, struct.pack(">I", n) + bytes([LABEL_ROTATING_ID]))[:4]


def nonce(device_id: int, day: int, slot: int, n: int) -> bytes:
    return struct.pack(">IHBI", device_id, day, slot, n)


def seal(secret, device_id, day, slot, n, plaintext: bytes) -> bytes:
    dk = day_key(secret, device_id, day, slot)
    rid = rotating_id(dk, n)
    aad = rid + bytes([PROTOCOL_VERSION])
    sealed = AESCCM(enc_key(dk), tag_length=TAG_BYTES).encrypt(nonce(device_id, day, slot, n), plaintext, aad)
    return rid + sealed  # rid(4) | ciphertext(8) | tag(4)


def time_sync(provision_key, device_id, unix: int) -> bytes:
    tag = hmac256(provision_key, struct.pack(">II", device_id, unix) + bytes([LABEL_TIME_SYNC]))[:12]
    return struct.pack("<I", unix) + tag


CASES = [
    # (name, day, slot, n, plaintext). Byte 1 bits 6-7: 01 Settings, 10 Arm, 11 Disarm.
    ("arm_slot1_n0", 256, 1, 0, bytes([0x00, 0x80, 0, 0, 0x1E, 0x02, 0x00, 0x00])),
    ("disarm_slot7_n15", 256, 7, 15, bytes([0x00, 0xC0, 0, 0, 0x9F, 0x05, 0xAA, 0xBB])),
    ("settings_slot0_n3", 257, 0, 3, bytes([0x04, 0x62, 128, 200, 0x00, 0x00, 0x00, 0x00])),
]
TIME_SYNC_UNIX = 1767225600 + 256 * 86400 + 4 * 3600 + 3723  # day 256, 05:02:03 UTC

BANNER = "GENERATED by tools/gen_access_vectors.py - DO NOT EDIT BY HAND."


def cpp_bytes(b: bytes) -> str:
    return "{ " + ", ".join(f"0x{x:02X}" for x in b) + " }"


def dart_bytes(b: bytes) -> str:
    return "<int>[" + ", ".join(f"0x{x:02X}" for x in b) + "]"


def main():
    here = pathlib.Path(__file__).resolve().parent.parent
    cpp = [f"// {BANNER}", "", "#pragma once", "", "#include <cstdint>", "", "namespace alc::access::vectors", "{", ""]
    cpp.append(f"  constexpr uint8_t M_SECRET[32] {cpp_bytes(SECRET)};")
    cpp.append(f"  constexpr uint8_t M_PROVISION_KEY[32] {cpp_bytes(PROVISION_KEY)};")
    cpp.append(f"  constexpr uint32_t M_DEVICE_ID {{ 0x{DEVICE_ID:08X} }};")
    cpp.append("")
    cpp.append("  struct CommandVector")
    cpp.append("  {")
    cpp.append("      uint16_t day;")
    cpp.append("      uint8_t slot;")
    cpp.append("      uint32_t n;")
    cpp.append("      uint8_t dayKey[32];")
    cpp.append("      uint8_t encKey[16];")
    cpp.append("      uint8_t rotatingId[4];")
    cpp.append("      uint8_t plaintext[8];")
    cpp.append("      uint8_t onAir[16];")
    cpp.append("  };")
    cpp.append("")
    cpp.append(f"  constexpr CommandVector M_COMMANDS[{len(CASES)}] {{")
    dart = [f"// {BANNER}", "", f"const List<int> kVectorSecret = {dart_bytes(SECRET)};",
            f"const List<int> kVectorProvisionKey = {dart_bytes(PROVISION_KEY)};",
            f"const int kVectorDeviceId = 0x{DEVICE_ID:08X};", "",
            "class CommandVector {",
            "  const CommandVector(this.day, this.slot, this.n, this.dayKey, this.encKey, this.rotatingId, this.plaintext, this.onAir);",
            "  final int day, slot, n;",
            "  final List<int> dayKey, encKey, rotatingId, plaintext, onAir;",
            "}", "", "const List<CommandVector> kCommandVectors = <CommandVector>["]
    for name, day, slot, n, pt in CASES:
        dk = day_key(SECRET, DEVICE_ID, day, slot)
        ek = enc_key(dk)
        rid = rotating_id(dk, n)
        air = seal(SECRET, DEVICE_ID, day, slot, n, pt)
        cpp.append(f"    // {name}")
        cpp.append(f"    {{ {day}, {slot}, {n}, {cpp_bytes(dk)}, {cpp_bytes(ek)}, {cpp_bytes(rid)}, {cpp_bytes(pt)}, {cpp_bytes(air)} }},")
        dart.append(f"  // {name}")
        dart.append(f"  CommandVector({day}, {slot}, {n}, {dart_bytes(dk)}, {dart_bytes(ek)}, {dart_bytes(rid)}, {dart_bytes(pt)}, {dart_bytes(air)}),")
    cpp.append("  };")
    cpp.append("")
    ts = time_sync(PROVISION_KEY, DEVICE_ID, TIME_SYNC_UNIX)
    cpp.append(f"  constexpr uint32_t M_TIME_SYNC_UNIX {{ {TIME_SYNC_UNIX} }};")
    cpp.append(f"  constexpr uint8_t M_TIME_SYNC_ON_AIR[16] {cpp_bytes(ts)};")
    cpp += ["", "}", ""]
    dart.append("];")
    dart.append("")
    dart.append(f"const int kVectorTimeSyncUnix = {TIME_SYNC_UNIX};")
    dart.append(f"const List<int> kVectorTimeSyncOnAir = {dart_bytes(ts)};")
    dart.append("")

    cpp_path = here / "src" / "access_vectors.hpp"
    cpp_path.write_text("\n".join(cpp))
    print(f"wrote {cpp_path}")
    dart_path = here.parent / "class_app" / "test" / "access_vectors.dart"
    if dart_path.parent.exists():
        dart_path.write_text("\n".join(dart))
        print(f"wrote {dart_path}")
    else:
        print(f"skipped {dart_path} (app not scaffolded yet)")


if __name__ == "__main__":
    main()
