#!/usr/bin/env python3
"""Writes the class_app bench credentials from THIS repo's credentials.conf.

BENCH ONLY. The output holds a device secret and a provisioning key, which the
production app must never contain. It is written to a gitignored file in
class_app so it cannot be committed there, and it is generated rather than typed
so the app and the firmware cannot disagree about the keys.

Run from the class_mfs_1 root:
    python3 tools/gen_bench_credentials.py
"""
import pathlib
import re
import sys

KEYS = ("CONFIG_MFS_DEVICE_ID", "CONFIG_MFS_DEVICE_SECRET", "CONFIG_MFS_PROVISION_KEY", "CONFIG_ALC_DEVICE_SERIAL")
LENGTHS = {"CONFIG_MFS_DEVICE_ID": 8, "CONFIG_MFS_DEVICE_SECRET": 64, "CONFIG_MFS_PROVISION_KEY": 64}


def parse(path: pathlib.Path) -> dict:
    values = {}
    for line in path.read_text().splitlines():
        match = re.match(r'^(CONFIG_[A-Z0-9_]+)="([^"]*)"\s*$', line.strip())
        if match and match.group(1) in KEYS:
            values[match.group(1)] = match.group(2)
    for key in KEYS:
        if key not in values:
            sys.exit(f"{path}: {key} is missing")
    for key, length in LENGTHS.items():
        if not re.fullmatch(rf"[0-9A-Fa-f]{{{length}}}", values[key]):
            sys.exit(f"{path}: {key} must be exactly {length} hex digits")
    # CLASS serial: MODEL-MMYY-NNNNN - 4-character model, month and year made,
    # number in the batch as 5 hex digits (e.g. MFS1-0926-00001).
    if not re.fullmatch(r"[A-Z0-9]{4}-(0[1-9]|1[0-2])[0-9]{2}-[0-9A-F]{5}", values["CONFIG_ALC_DEVICE_SERIAL"]):
        sys.exit(f"{path}: CONFIG_ALC_DEVICE_SERIAL must be MODEL-MMYY-NNNNN, e.g. MFS1-0926-00001")
    if values["CONFIG_MFS_DEVICE_SECRET"].upper() == values["CONFIG_MFS_PROVISION_KEY"].upper():
        sys.exit(f"{path}: the device secret and provisioning key must differ")
    return values


def dart_bytes(hex_string: str) -> str:
    return "<int>[" + ", ".join(f"0x{hex_string[i:i + 2].upper()}" for i in range(0, len(hex_string), 2)) + "]"


def main():
    here = pathlib.Path(__file__).resolve().parent.parent
    values = parse(here / "credentials.conf")
    out = here.parent / "class_app" / "lib" / "services" / "bench_credentials.dart"
    if not out.parent.exists():
        sys.exit(f"{out.parent} does not exist - scaffold class_app first")
    out.write_text("\n".join([
        "// GENERATED by class_mfs_1/tools/gen_bench_credentials.py - DO NOT EDIT OR COMMIT.",
        "// BENCH ONLY: the production app must never hold a device secret.",
        "",
        f"const String kBenchDeviceLabel = '{values['CONFIG_ALC_DEVICE_SERIAL']}';",
        f"const int kBenchDeviceId = 0x{values['CONFIG_MFS_DEVICE_ID'].upper()};",
        f"const List<int> kBenchDeviceSecret = {dart_bytes(values['CONFIG_MFS_DEVICE_SECRET'])};",
        f"const List<int> kBenchProvisionKey = {dart_bytes(values['CONFIG_MFS_PROVISION_KEY'])};",
        "",
    ]))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
