#!/usr/bin/env python3
"""Generates the MFS_1 parameter encoding tables for BOTH firmware and app.

The two sides must agree byte for byte. Evaluating the formula independently in
C++ and Dart risks a one-LSB divergence at some inputs, which would mean a
slider position meaning two different things. Generating once removes the
possibility rather than testing for it.

Run from the class_mfs_1 root:
    python3 tools/gen_protocol_tables.py
"""
import pathlib

# Sensitivity: THRESH_ACT in 13-bit LSB at 0.25 mg/LSB. Byte 255 is MOST
# sensitive, i.e. the LOWEST threshold - the app's slider runs insensitive-left.
THRESHOLD_MAX_LSB = 4000   # 1000 mg, least sensitive, byte 0
THRESHOLD_MIN_LSB = 40     # 10 mg, most sensitive, byte 255

# Cooldown in seconds. Byte 0 means no cooldown; 1..255 spans 1 s to 3600 s.
COOLDOWN_MAX_SECS = 3600

def threshold(byte: int) -> int:
    return round(THRESHOLD_MAX_LSB * (THRESHOLD_MIN_LSB / THRESHOLD_MAX_LSB) ** (byte / 255))

def cooldown(byte: int) -> int:
    return 0 if byte == 0 else round(COOLDOWN_MAX_SECS ** ((byte - 1) / 254))

def delay(code: int) -> int:
    """Trigger delay in seconds. Seven bits, piecewise, fully contiguous:
         0..59   -> V seconds        (0 s .. 59 s)
        60..118  -> V-59 minutes     (1 min .. 59 min)
       119..127  -> V-118 hours      (1 h .. 9 h)
    Contiguous at both seams: 59->59 s and 60->60 s; 118->3540 s and 119->3600 s.
    No code means two things, and there are no gaps."""
    if code < 60:
        return code
    if code < 119:
        return (code - 59) * 60
    return (code - 118) * 3600

BANNER = "GENERATED by tools/gen_protocol_tables.py - DO NOT EDIT BY HAND."

def rows(fn, count=256, per_line=8):
    values = [fn(b) for b in range(count)]
    return [values[i:i + per_line] for i in range(0, count, per_line)]

def write_cpp(path: pathlib.Path):
    out = [f"// {BANNER}", "// Regenerate after changing the formula, and commit both outputs.",
           "", "#pragma once", "", "#include <cstdint>", "", "namespace alc::protocol", "{", ""]
    for name, fn, count, comment in (
        ("M_THRESHOLD_TABLE", threshold, 256, "Sensitivity byte -> ADXL367 THRESH_ACT in LSB (0.25 mg each)."),
        ("M_COOLDOWN_TABLE", cooldown, 256, "Cooldown byte -> seconds. Index 0 is 'no cooldown'."),
        ("M_DELAY_TABLE", delay, 128, "Delay code (7 bits) -> seconds before the trigger fires."),
    ):
        out.append(f"  // {comment}")
        out.append(f"  constexpr uint16_t {name}[{count}] {{")
        for row in rows(fn, count=count):
            out.append("    " + ", ".join(f"{v:5d}" for v in row) + ",")
        out.append("  };")
        out.append("")
    out += ["}", ""]
    path.write_text("\n".join(out))
    print(f"wrote {path}")

def write_dart(path: pathlib.Path):
    if not path.parent.exists():
        print(f"skipped {path} (app not scaffolded yet)")
        return
    out = [f"// {BANNER}", "// Regenerate after changing the formula, and commit both outputs.", ""]
    for name, fn, count, comment in (
        ("kThresholdTable", threshold, 256, "Sensitivity byte -> ADXL367 THRESH_ACT in LSB (0.25 mg each)."),
        ("kCooldownTable", cooldown, 256, "Cooldown byte -> seconds. Index 0 is 'no cooldown'."),
        ("kDelayTable", delay, 128, "Delay code (7 bits) -> seconds before the trigger fires."),
    ):
        out.append(f"/// {comment}")
        out.append(f"const List<int> {name} = <int>[")
        for row in rows(fn, count=count):
            out.append("  " + ", ".join(str(v) for v in row) + ",")
        out.append("];")
        out.append("")
    path.write_text("\n".join(out))
    print(f"wrote {path}")

if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent.parent
    write_cpp(here / "src" / "mfs_protocol_tables.hpp")
    write_dart(here.parent / "class_app" / "lib" / "protocol" / "tables.dart")
